### ISSUE TITLE
Mod is broken in how it handles config files

### ISSUE THREAD

**Issue by songpola** [TexBlock/RubidiumZoomer#1]
Full Crash Reports: [crash-2022-10-10_13.19.26-fml.txt](https://github.com/TexTrueStudio/RubidiumToolkit/files/9743689/crash-2022-10-10_13.19.26-fml.txt)

```
Caused by 0: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
```

```
Exception message: java.nio.file.NoSuchFileException: F:\CurseForge\Instances\IFEX\config\RubidiumToolkit\rubidium-toolkit.toml
```

I've done some searching and found a [workaround](https://forums.minecraftforge.net/topic/105995-error-comelectronwillnightconfigcoreiowritingexception-an-io-error-occured-happens-every-time-i-open-forge/#comment-474221) by manually create the file (config/RubidiumToolkit/rubidium-toolkit.toml in this case) and it actually works!

**Comment by TexBlock** [comment]
Sorry, just saw it now.
I'll fix this in a few days, because I've been a little busy lately.

**Comment by TexBlock** [comment]
Fixed [mc1.16.5-v1.0.3](https://github.com/TexTrueStudio/RubidiumToolkit/tree/mc1.16.5-v1.0.3)
But I can't upload curseforge now.
