### ISSUE TITLE
[BUG]调视频设置调崩了（Crash in save video settings）

### ISSUE THREAD

**Issue by Kasualix** [TexBlock/RubidiumZoomer#4]
crash report: https://pastebin.ubuntu.com/p/PmyPKrnfnJ/
latest.log: https://pastebin.ubuntu.com/p/9VphwPWqyg/

1.0.4 config 消失了（

**Comment by TexBlock** [comment]
草

**Comment by TexBlock** [comment]
给一下整合包，我测试一下 @Kasualix

**Comment by Kasualix** [comment]
[Tankoptimization-dev.zip](https://github.com/TexTrueStudio/RubidiumToolkit/files/10554021/Tankoptimization-dev.zip)

**Comment by TexBlock** [comment]
草，一会发个hotfix

**Comment by TexBlock** [comment]
大约今晚发（不出意外的话）

**Comment by TexBlock** [comment]
已在 [mc1.16.5-v1.0.4-hotfix1](https://github.com/TexTrueStudio/RubidiumToolkit/releases/tag/mc1.16.5-v1.0.4-hotfix1) 修复。

Fixed in [mc1.16.5-v1.0.4-hotfix1](https://github.com/TexTrueStudio/RubidiumToolkit/releases/tag/mc1.16.5-v1.0.4-hotfix1).
